### ISSUE TITLE
An error occurred while running the Dealer's Life 2 example

### ISSUE THREAD

**Issue by yakami129** [BAAI-Agents/Cradle#29]
- Run command
`
 python runner.py --envConfig "./conf/env_config_dealers.json"
`

- ERROR LOG
`
Traceback (most recent call last):
  File "E:\code\github\Cradle\runner.py", line 49, in <module>
    main(args)
  File "E:\code\github\Cradle\runner.py", line 33, in main
    entry(args)
  File "E:\code\github\Cradle\cradle\runner\dealers_runner.py", line 199, in entry
    pipelineRunner = PipelineRunner(llm_provider,
  File "E:\code\github\Cradle\cradle\runner\dealers_runner.py", line 49, in __init__
    self.set_internal_params()
  File "E:\code\github\Cradle\cradle\runner\dealers_runner.py", line 55, in set_internal_params
    self.skill_registry = DealersSkillRegistry(
  File "E:\code\github\Cradle\cradle\utils\singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "E:\code\github\Cradle\cradle\environment\dealers\skill_registry.py", line 57, in __init__
    super(DealersSkillRegistry, self).__init__(skill_from_default=skill_from_default,
  File "E:\code\github\Cradle\cradle\environment\skill_registry.py", line 100, in __init__
    self.skills = self.load_skills_from_scripts()
  File "E:\code\github\Cradle\cradle\environment\skill_registry.py", line 180, in load_skills_from_scripts
    self.store_skills_to_file(os.path.join(config.skill_local_path, self.skill_library_filename), skills)
  File "E:\code\github\Cradle\cradle\environment\skill_registry.py", line 515, in store_skills_to_file
    save_json(file_path, serialized_skills, indent=4)
  File "E:\code\github\Cradle\cradle\utils\json_utils.py", line 100, in save_json
    with open(file_path, mode='w', encoding='utf8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './res/dealers/skills/skill_lib_basic.json'
`

**Comment by DVampire** [comment]
Sorry for the late reply, because we didn't upload the json file of dealers' skill before, but we have already done the processing in the code to automatically regenerate the json file. Here is what you need to do:

1. please modify the ./cradle/config/config.py
set `self.skill_from_default = False` in line 163
2. make a dir in ./res/dealers named skills
`mkdir ./res/dealers/skills`

If you encounter any issues, please feel free to raise an issue for us. Thanks

**Comment by tellarin** [comment]
We will have a fix merged into the code in the next couple days too.
